### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by CatchDr** [lukas-blecher/LaTeX-OCR#102]
eqs = open(equations, 'r',encoding="utf-8").read().split('\n')

Traceback (most recent call last):
    dataset = Im2LatexDataset(equations, images, args.tokenizer)
  File "dataset/dataset.py", line 85, in __init__
    eqs = open(equations, 'r').read().split('\n')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 29191547: illegal multibyte sequence

**Comment by lukas-blecher** [comment]
your text file is not encoded in utf-8. `0xbd` is the ½ character in Latin-1. You need to process the equation file e.g. using https://github.com/lukas-blecher/LaTeX-OCR/blob/main/dataset/preprocessing/preprocess_formulas.py
