### ISSUE TITLE
Is there any limit on the number of trainset image?

### ISSUE THREAD

**Issue by JuneKwon9** [lukas-blecher/LaTeX-OCR#103]
Hi I working with my own dataset. When I use 120,000 of images and convert these images to train.pkl, it works. But when I use over 800,000 of images and convert these images to pickle file, it only works  187,185 images. Is there any limit of number when convert to trainset.pkl?

**Comment by JuneKwon9** [comment]
sry, I miss the filename extension.

**Comment by sravanthOppo27** [comment]
Can I get the link of the dataset ?
