### ISSUE TITLE
[Bug] Webview doesn't show.

### ISSUE THREAD

**Issue by kxxt** [lukas-blecher/LaTeX-OCR#109]
Hi, 
I'm currently using this application under Manjaro Linux with gnome (material-shell).

There are several issues now.

The most severe issue is that the webview doesn't show. I can't see rendered math equations.

![image](https://user-images.githubusercontent.com/18085551/160630249-0515f707-f0e3-48f9-9307-71757f557163.png)

<details>
<summary>
neofetch outputs
</summary>
<pre>
██████████████████  ████████   kxxt@laptop 
██████████████████  ████████   ----------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: HP Spectre x360 Convertible 15 
████████            ████████   Kernel: 5.15.28-1-MANJARO 
████████  ████████  ████████   Uptime: 14 hours, 33 mins 
████████  ████████  ████████   Packages: 2145 (pacman) 
████████  ████████  ████████   Shell: zsh 5.8.1 
████████  ████████  ████████   Resolution: 3840x2160, 3840x2160 
████████  ████████  ████████   DE: GNOME 41.4 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita-maia-compact-dark 
████████  ████████  ████████   Theme: Adwaita-dark [GTK2/3] 
████████  ████████  ████████   Icons: Adwaita [GTK2/3] 
                               Terminal: tmux 
                               CPU: Intel i7-10750H (12) @ 5.000GHz 
                               GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
                               GPU: Intel CometLake-H GT2 [UHD Graphics] 
                               Memory: 9268MiB / 15613MiB 
</pre>
</details>

I might be able to look into this issue when I have more spare time.

Thank you for this awesome application!

**Comment by lukas-blecher** [comment]
Hi, I don't know why it won't work for you. Sometimes the web engine doesn't work (#28). Maybe try reinstalling the PyQtWebEngine.
If the GUI doesn't work you can still use the cli version and capture the screenshots using a third party application (also related to your other issue #110)
It's not possible for me to test all linux distros out there. 
If you find the problem, feel free to report it here but for now I'm going to close the issue.

**Comment by lukas-blecher** [comment]
Ok I changed my mind. I'm letting it stay open as there was a related issue (#104) with the same problem but went got off-topic. I'll be closing this one instead

**Comment by kxxt** [comment]
After some investigation, I found a [solution](https://stackoverflow.com/questions/59987649/qwebengineview-not-showing-anything-on-windows-10).

Set environment variable `QTWEBENGINE_DISABLE_SANDBOX` to `1` solves this problem. :tada:

**Comment by kxxt** [comment]
Set the environment variable before creating `QApplication` instance solves this issue completely.

```python
os.environ['QTWEBENGINE_DISABLE_SANDBOX'] = ''
app = QApplication(sys.argv)
```
But perhaps whether or not to disable the sandbox feature should be decided by the user.
