### ISSUE TITLE
[Feature] Add a cmdline option to use `gnome-screenshot` instead of pyqt to capture screenshots

### ISSUE THREAD

**Issue by kxxt** [lukas-blecher/LaTeX-OCR#110]
Under linux, it is possible to use `gnome-screenshot` to capture screenshots which makes multiple monitor support very easy. #57 

The implementation is very trivial and I can open a pull request for that soon.

**Comment by lukas-blecher** [comment]
I'm happy about all contributions!

**Comment by kxxt** [comment]
This feature is now implemented in #111 . 
I do need to make more tweaks to make GUI fully work under linux.
