### ISSUE TITLE
MacOS with pixel doubling caused ImageGrab Error

### ISSUE THREAD

**Issue by backtraxe** [lukas-blecher/LaTeX-OCR#118]
In MacOS, turning on pixel doubling will cause a difference between the real resolution and the display resolution, which will affect the screenshots of ImageGrab.

For me, my monitor's real resolution is 3840x2160, after pixel doubling, it becomes 1920x1080, so the use of `ImageGrab.grab(bbox=(x1, y1, x2, y2))` caused `PIL.UnidentifiedImageError`.

To solve the problem,

1. Check your monitor's real resolution. (For me is 3840x2160)
2.  Check your displayed resolution. (For me is 1920x1080)

```python
import tkinter as tk
root = tk.Tk()
print(root.winfo_screenwidth())
print(root.winfo_screenheight())
root.destroy()
```

3. I use `ImageGrab.grab()` for whole screenshot, then crop it.

`gui.py`, line 266

```python
factor = 3840 / 1920 # repalced with your real resolution / displayed resolution
img = ImageGrab.grab()
img = img.crop((x1*factor, y1*factor, x2*factor, y2*factor))
```

**Comment by lukas-blecher** [comment]
seems to be the same issue as in https://github.com/python-pillow/Pillow/issues/6144
Can you check if your Pillow version is 9.1.0 and try again?

**Comment by backtraxe** [comment]
> seems to be the same issue as in [python-pillow/Pillow#6144](https://github.com/python-pillow/Pillow/issues/6144) Can you check if your Pillow version is 9.1.0 and try again?

My Pillow version is 9.1.0.

**Comment by lukas-blecher** [comment]
Can quickly check what happens with version 9.0.0?
