### ISSUE TITLE
【❓question】`No module named 'pix2tex'` when I execute `dataset.py`, how can I run it without `pip install pix2tex`?

### ISSUE THREAD

**Issue by TITC** [lukas-blecher/LaTeX-OCR#124]
I am reading your code for learning. And after yesterday's commit, I can't run [`dataset.py`](https://github.com/lukas-blecher/LaTeX-OCR/blob/main/pix2tex/dataset/dataset.py) directly.
```shell
cd ./LaTeX-OCR
python pix2tex/dataset/dataset.py -i handwritten -e CROHME_math.txt -t tokenizer.json -o data/train.pkl
```
it reports `No module named 'pix2tex'` Exception. I know [some ways](https://stackoverflow.com/a/4383597/11430711) to let it work but not elegant.
such as append path at dataset.py
```python
import sys
# # insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, './LaTeX-OCR')
```
or append path at vscode [launch.json](https://stackoverflow.com/a/53624143/11430711) `env`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {"PYTHONPATH": "${PYTHONPATH}:${workspaceRoot}"},
            "args": [
                "-i",
                "/mnt/d/git_repository/LaTeX-OCR/dataset/data/handwritten",
                "-e",
                "/mnt/d/git_repository/LaTeX-OCR/dataset/data/CROHME_math.txt",
                "-t",
                "/mnt/d/git_repository/LaTeX-OCR/dataset/tokenizer.json",
                "-o",
                "/mnt/d/git_repository/LaTeX-OCR/dataset/data/train.pkl"
            ],
        }
    ]
}

```
But I also found [an answer](https://stackoverflow.com/a/21995949/11430711) as below.
> Nothing wrong with:
`from application.app.folder.file import func_name`
>Just make sure folder also contains an `__init__.py`, this allows it to be included as a package. Not sure why the other answers talk about `PYTHONPATH`.

furthermore, I found that is what you have done already.
![image](https://user-images.githubusercontent.com/35098797/163516124-4cd8ae2e-cbc3-4626-bc6f-410989275985.png)

but it's not work in my situation, have you encountered such problem and how can I fix it?

**Comment by lukas-blecher** [comment]
I think the easiest way would be to run
```
pip install -e .
```
when you are in the project root. This way the package is installed but not in `site-packages` but your local copy. So changes to the repo will be recognized

**Comment by TITC** [comment]
> pip install -e .

I don't know what to say, you are so brilliant.
