### ISSUE TITLE
how to convert my own latex line to yours like math.txt?

### ISSUE THREAD

**Issue by JaosonMa** [lukas-blecher/LaTeX-OCR#132]
here is my own latex data line ,there is no space .
![image](https://user-images.githubusercontent.com/23551774/164603967-304a34e5-bfdc-44d2-a405-611d5fe9ed65.png)
here is you math.txt latex line, there is lots of sapce in the line ,
![image](https://user-images.githubusercontent.com/23551774/164604040-472a0a3d-a06f-463d-a96b-0e9c8ead4215.png)
i want to konw how to convert my own latex line to you style?

**Comment by lukas-blecher** [comment]
I'm using a normalization first introduced in the Harvard paper (https://github.com/harvardnlp/im2markup)

It is located in `pix2tex/dataset/preprocessing/preprocess_formulas.py`. To normalize your file simply execute
```bash
python -m pix2tex.dataset.preprocessing.preprocess_formulas -i path/to/math.txt -o math.norm.txt
```

**Comment by JaosonMa** [comment]
here is my config
![image](https://user-images.githubusercontent.com/23551774/168569578-e07d7e53-c3f0-4772-9e57-899a5d5cfd3f.png)

this is  the gif

![train_40_10-mid2error](https://user-images.githubusercontent.com/23551774/168570698-0a52a36f-b37f-4f9e-aee7-e8dc25279d1a.gif)

**Comment by JaosonMa** [comment]
> I'm using a normalization first introduced in the Harvard paper (https://github.com/harvardnlp/im2markup)
> 
> It is located in `pix2tex/dataset/preprocessing/preprocess_formulas.py`. To normalize your file simply execute
> 
> ```shell
> python -m pix2tex.dataset.preprocessing.preprocess_formulas -i path/to/math.txt -o math.norm.txt
> ```
> 
> Edit: I think you will need to install Nodejs if you don't already have

use pip install Nodejs , install successfully

then use pix2tex.dataset.preprocessing.preprocess_formulas
![image](https://user-images.githubusercontent.com/23551774/168572762-ff4391d3-6a36-466f-9ce1-2737ba9dfe86.png)

i didn't found something that useful for this , please help me again.

this is the test input latex lines:
`
\frac{17\pi }{6}
\frac{\sqrt{2}-1}{2}<1
\left|-\frac{1}{2} \right|=0.5
{{\complement}_{U}}B=\left\{ 1,4 \right\}
`

**Comment by lukas-blecher** [comment]
pip install? You need to install it from here https://nodejs.org/en/download/

**Comment by JaosonMa** [comment]
i got another Q, 
here is my own data's 15st lines,
with this code 
`python -m pix2tex.dataset.preprocessing.preprocess_formulas -i path/to/math.txt -o math.norm.txt`

some line was missed, i can not slove this. 
`\sin (\pi  + \alpha ) + \cos (\frac{\pi }{2} + \alpha ) =  - m \Rightarrow  - \sin \alpha  - \sin \alpha  =  - m \Rightarrow \sin \alpha  = \frac{m}{2}
C = A \cup B
P(C) = P(A \cup B) = {\rm{ }}P(A) + P(B) = 0.5
D
0.90
14
6
A
B
y = {x^{ - 2}}
\frac{1}{{16}}
y = {x^{\frac{1}{2}}}
0 < x < 1
y = - {x^2} + 2x
PF = MF` 

![error](https://user-images.githubusercontent.com/23551774/169863167-a1bb6e1c-b8d3-4c28-8444-eb829b1f1030.png)

**Comment by lukas-blecher** [comment]
for the equations you posted I get
```tex
\sin ( \pi + \alpha ) + \cos ( \frac { \pi } { 2 } + \alpha ) = - m \Rightarrow - \sin \alpha - \sin \alpha = - m \Rightarrow \sin \alpha = \frac { m } { 2 }
P ( C ) = P ( A \cup B ) = \mathrm { { } } P ( A ) + P ( B ) = 0 . 5
y = { x ^ { - 2 } }
\frac { 1 } { { 1 6 } }
y = { x ^ { \frac { 1 } { 2 } } }
y = - { x ^ { 2 } } + 2 x
```
The others get deleted here: 
https://github.com/lukas-blecher/LaTeX-OCR/blob/9f974c9c855535e1d1435236f7367cbefe6bbdda/pix2tex/dataset/preprocessing/preprocess_formulas.py#L83

You can change it and you'll get
```tex
\sin ( \pi + \alpha ) + \cos ( \frac { \pi } { 2 } + \alpha ) = - m \Rightarrow - \sin \alpha - \sin \alpha = - m \Rightarrow \sin \alpha = \frac { m } { 2 }
C = A \cup B
P ( C ) = P ( A \cup B ) = \mathrm { { } } P ( A ) + P ( B ) = 0 . 5
D
0 . 9 0
1 4
6
A
B
y = { x ^ { - 2 } }
\frac { 1 } { { 1 6 } }
y = { x ^ { \frac { 1 } { 2 } } }
0 < x < 1
y = - { x ^ { 2 } } + 2 x
P F = M F
```

**Comment by JaosonMa** [comment]
after change the code , i got the same output , but also got another error with this line 
`{T_n} = \left\{ \begin{gathered}     - {S_n} =  - {n^2} + 6n\quad (n \leqslant 3) \hfill \\    {S_n} - 2{S_3} = {n^2} - 6n + 18\quad (n \geqslant 4) \hfill \\   \end{gathered}  \right.`

![image](https://user-images.githubusercontent.com/23551774/169921545-616166dd-81a9-4d42-9a2e-458c0f0bdeac.png)

the line is worker well ,
![image](https://user-images.githubusercontent.com/23551774/169921592-ea5e4b88-1a0b-4eb1-930c-30bab9ccfd67.png)
,  there also other lines like this error,

**Comment by TITC** [comment]
> after change the code , i got the same output 

I will take a look later.

---
> the line is worker well , 

I noticed LaTex compile will ignore grammar error, but such sample could be a kind of mislead for model. In fact, it filtered by syntax tree construct by KaTex parser.  More detail can view [Image-to-Markup Generation with Coarse-to-Fine Attention](https://arxiv.org/pdf/1609.04938.pdf).

![image](https://user-images.githubusercontent.com/35098797/169934122-6f5fab9f-c213-4567-a601-67ac43063316.png)

The error seems normal, introduced at [im2markup](https://github.com/harvardnlp/im2markup).
> The above command will normalize the formulas. Note that this command will produce some error messages since some formulas cannot be parsed by the KaTeX parser.

Here is a method to check wether or not the formula is grammar correct, copy that and paste at [this site](https://sixthform.info/katex/examples/demo.html).

![image](https://user-images.githubusercontent.com/35098797/169935113-e7ce1d06-df8f-42fa-80f1-939b5932f166.png)

Here is above LaTex code
```tex
\subsection*{Taylor's Theorem} 
Then
\[
 f(x)=f(a)+f'(a)(x-a)+\cdots+\frac{f^{(n)}(a)}{n!}(x-a)^n+R_n(x)
\]
where
\[
 {T_n} = \left\{ \begin{gathered} - {S_n} = - {n^2} + 6n\quad (n \leqslant 3) \hfill \\ {S_n} - 2{S_3} = {n^2} - 6n + 18\quad (n \geqslant 4) \hfill \\ \end{gathered} \right.
\]
for some $c$ between $a$ and $x$.
```

Here is the latest Chinese version LaTex [manual](https://ctan.mirrors.hoobly.com/info/lshort/chinese/lshort-zh-cn.pdf). And `\hfill` is a [macro ](https://tex.stackexchange.com/a/45952) used to control distance between text not a LaTex math code or font code. I think It's reasonable not pass KaTex parser.

If I am wrong in any way, please do correct me, thank you!

**Comment by TITC** [comment]
> after change the code , i got the same output 

I will take a look later.

---
> the line is worker well , 

I noticed LaTex compile will ignore grammar error, but such sample could be a kind of mislead for model. In fact, it filtered by syntax tree construct by KaTex parser.  More detail can view [Image-to-Markup Generation with Coarse-to-Fine Attention](https://arxiv.org/pdf/1609.04938.pdf).

![image](https://user-images.githubusercontent.com/35098797/169934122-6f5fab9f-c213-4567-a601-67ac43063316.png)

The error seems normal, introduced at [im2markup](https://github.com/harvardnlp/im2markup).
> The above command will normalize the formulas. Note that this command will produce some error messages since some formulas cannot be parsed by the KaTeX parser.

Here is a method to check wether or not the formula is grammar correct, copy that and paste at [this site](https://sixthform.info/katex/examples/demo.html).

![image](https://user-images.githubusercontent.com/35098797/169935113-e7ce1d06-df8f-42fa-80f1-939b5932f166.png)

Here is above LaTex code
```tex
\subsection*{Taylor's Theorem} 
Then
\[
 f(x)=f(a)+f'(a)(x-a)+\cdots+\frac{f^{(n)}(a)}{n!}(x-a)^n+R_n(x)
\]
where
\[
 {T_n} = \left\{ \begin{gathered} - {S_n} = - {n^2} + 6n\quad (n \leqslant 3) \hfill \\ {S_n} - 2{S_3} = {n^2} - 6n + 18\quad (n \geqslant 4) \hfill \\ \end{gathered} \right.
\]
for some $c$ between $a$ and $x$.
```

Here is the latest Chinese version LaTex [manual](https://ctan.mirrors.hoobly.com/info/lshort/chinese/lshort-zh-cn.pdf). And `\hfill` is a [macro ](https://tex.stackexchange.com/a/45952) used to control distance between text not a LaTex math code or font code. I think It's reasonable not pass KaTex parser.

If I am wrong in any way, please do correct me, thank you!

**Comment by TITC** [comment]
> after change the code , i got the same output 

I will take a look later.

---
> the line is worker well , 

I noticed LaTex compile will ignore grammar error, but such sample could be a kind of mislead for model. In fact, it filtered by syntax tree construct by KaTex parser.  More detail can view [Image-to-Markup Generation with Coarse-to-Fine Attention](https://arxiv.org/pdf/1609.04938.pdf).

![image](https://user-images.githubusercontent.com/35098797/169934122-6f5fab9f-c213-4567-a601-67ac43063316.png)

The error seems normal, introduced at [im2markup](https://github.com/harvardnlp/im2markup).
> The above command will normalize the formulas. Note that this command will produce some error messages since some formulas cannot be parsed by the KaTeX parser.

Here is a method to check wether or not the formula is grammar correct, copy that and paste at [this site](https://sixthform.info/katex/examples/demo.html).

![image](https://user-images.githubusercontent.com/35098797/169935113-e7ce1d06-df8f-42fa-80f1-939b5932f166.png)

Here is above LaTex code
```tex
\subsection*{Taylor's Theorem} 
Then
\[
 f(x)=f(a)+f'(a)(x-a)+\cdots+\frac{f^{(n)}(a)}{n!}(x-a)^n+R_n(x)
\]
where
\[
 {T_n} = \left\{ \begin{gathered} - {S_n} = - {n^2} + 6n\quad (n \leqslant 3) \hfill \\ {S_n} - 2{S_3} = {n^2} - 6n + 18\quad (n \geqslant 4) \hfill \\ \end{gathered} \right.
\]
for some $c$ between $a$ and $x$.
```

Here is the latest Chinese version LaTex [manual](https://ctan.mirrors.hoobly.com/info/lshort/chinese/lshort-zh-cn.pdf). And `\hfill` is a [macro ](https://tex.stackexchange.com/a/45952) used to control distance between text not a LaTex math code or font code. I think It's reasonable not pass KaTex parser.

If I am wrong in any way, please do correct me, thank you!

**Comment by TITC** [comment]
> after change the code , i got the same output

https://github.com/lukas-blecher/LaTeX-OCR/blob/9f974c9c855535e1d1435236f7367cbefe6bbdda/pix2tex/dataset/preprocessing/preprocess_formulas.py#L83
to
```python
if len(tokens_out) > 0:
```
output same with https://github.com/lukas-blecher/LaTeX-OCR/issues/132#issuecomment-1135203100

**Comment by JaosonMa** [comment]
i missed some words , i got the same result with you , lines was not deleted.
@TITC  i am not sure you are right or not , I don't know much about the format differences of latex or KAtex。
what i done is  repleace all the `\begin{gathered}` with `\begin{array}` ,then the error gone ,but there alse other errors, most of all i saw was the parse error, some was because chinese words, after changed `if len(tokens_out) > 5:` to `if len(tokens_out) >= 0:` , i can got an empty line if the line was parse error, then i run a bat to remove all the empty lines only save the right lines.
