### ISSUE TITLE
Alternative backbone checkpoint

### ISSUE THREAD

**Issue by tuantran23012000** [lukas-blecher/LaTeX-OCR#144]
I saw your model consists of a Vit encoder with a ResNet backbone and a Transformer decoder, so I want to ask some questions:
- What's the Resnet version?
- Can we use another pre-trained weight?

**Comment by lukas-blecher** [comment]
The backbone is defined here:
https://github.com/lukas-blecher/LaTeX-OCR/blob/4172b0bc29116a212c6acd415fbda3032f10ad0b/pix2tex/models.py#L111-L113

It's a [`ResNetV2`](https://github.com/rwightman/pytorch-image-models/blob/75144395739162a153dae5628320b85b5895634b/timm/models/resnetv2.py#L352) from the `timm` library. You have some control over e.g. the number of layers in the settings by changing the `backbone_layers` property.

The ViT and ResNet backbone are trained at the same time. I don't have another version available.

**Comment by lukas-blecher** [comment]
Feel free to reopen if you have further questions on that topic
