### ISSUE TITLE
Is there any change to convert the formulas to python?

### ISSUE THREAD

**Issue by dylbor96** [lukas-blecher/LaTeX-OCR#156]
Hi there, 
do you think it's possible to convert from image to latex code, and again from latex code to python?

Thanks

**Comment by TITC** [comment]
If you mean unexpected changes, no. more specific, there is no process to transfer LaTex code to python code.

the output of the project is a sequence of strings, and the string has a large probability follow LaTex grammar, so in that case it be rendered through the LaTex engine.

**Comment by lukas-blecher** [comment]
It's definitely possible but outside the scope of this project. 
I remember there is a repo that generates latex code from a python function but I can't find it at the moment. This would be a good starting point for your idea.

**Comment by lukas-blecher** [comment]
Here: https://github.com/google/latexify_py
This could help you. Use some translation language model and generate a dataset with the repo above.
