### ISSUE TITLE
Equation view not working in GUI

### ISSUE THREAD

**Issue by kinalmehta** [lukas-blecher/LaTeX-OCR#164]
I created a new conda environment and installed using `pip install pix2tex[gui]`
I also tried cloning and then installing using `pip install .[gui]`
Both resulted in the GUI not able to render the equations after solving for it
Below are the example images
![Screenshot from 2022-06-26 16-55-37](https://user-images.githubusercontent.com/19221028/175813323-d498ebd5-9961-49fc-b306-b6c3e12fd311.png)
![Screenshot from 2022-06-26 17-34-01](https://user-images.githubusercontent.com/19221028/175813326-78ee404f-0cd0-4726-878b-5ce09c920e05.png)
![Screenshot from 2022-06-26 17-34-24](https://user-images.githubusercontent.com/19221028/175813329-bd6c21be-a950-47bf-98f8-924f810eecf3.png)

You can see that the equation is calculated from the equation but the rendering is not visible. 

Any help on this would be appreciated. I'm also ready to solve it and help debug this with some guidance.

Other environment details
- Fedora 36
- Gnome 42
- x11 windowing system
- also tried with wayland but it failed to retrive screenshot

Thanks
Kinal

**Comment by lukas-blecher** [comment]
Hi, can you have a look at the following issue: https://github.com/lukas-blecher/LaTeX-OCR/issues/109#issuecomment-1084419413
I think that's the solution to your problem.

I forgot to add this flag by default. Didn't have the chance to test it yet.

**Comment by kinalmehta** [comment]
That worked, but is disabling sandboxing safe?
Thanks for the help and an amazing application/repo. :D

**Comment by lukas-blecher** [comment]
I have no idea. Good point though.
Thanks :)
