### ISSUE TITLE
Is there any way to speed up the weights downloading？

### ISSUE THREAD

**Issue by kermsite** [lukas-blecher/LaTeX-OCR#167]
I'm in China. I install the package from pypi mirror. 
However, when run `latexocr`, there are weights (97.4 M) to be downloaded, and it takes about two hours (15kb/s). 
Is there any way to speed up the weights downloading？

**Comment by lukas-blecher** [comment]
The weights are hosted on GitHub. You can try to download the directly here: https://github.com/lukas-blecher/LaTeX-OCR/releases/tag/v0.0.1 place them in `pix2tex/model/checkpoints`
I'm not sure what else I can do.

**Comment by kermsite** [comment]
Thank you! This solved my problem.
