### ISSUE TITLE
Resume training process when being interrupted

### ISSUE THREAD

**Issue by gggaugau** [lukas-blecher/LaTeX-OCR#171]
Hello. May I ask is there an option to resume training from a checkpoint? For example when I ctrl + C in the middle of training process and then how do I resume training from that part?
Thanks in advance

**Comment by lukas-blecher** [comment]
Yes, that's possible. With the saved checkpoints there is also a saved `config.yaml` file.
There should be an argument `load_chkpt` that points to the latest checkpoint. Just train with this new config file. Not sure if it is written automatically (it should) but check to be sure.

You can additionally pass the `--resume` flag if you want it to write to the same wandb session.
