### ISSUE TITLE
Poor performance with tensor equation & complex matrices

### ISSUE THREAD

**Issue by FrankFrank9** [lukas-blecher/LaTeX-OCR#199]
Example 1 
<img width="483" alt="Screenshot 2022-09-25 at 20 37 45" src="https://user-images.githubusercontent.com/91851558/192159872-2acf79d7-f054-4fb7-9911-de6f8debc442.png">
Original equation
<img width="641" alt="Screenshot 2022-09-25 at 20 39 03" src="https://user-images.githubusercontent.com/91851558/192159875-17d35c7f-68a2-4764-a73a-2a93e5e25d4e.png">

Example 2
Original
<img width="641" alt="Screenshot 2022-09-25 at 20 40 36" src="https://user-images.githubusercontent.com/91851558/192159899-d5af4ac6-3775-40fb-aa9b-1c23b1826ec9.png">

which is rendered as 
$\mathbf{U}=\left(\begin{array}{c c c c}{{u^{\prime}(x_{1},y_{1},t_{1})}}&{{\cdots}}&{{u^{\prime}(x_{N x},y_{N y},t_{1})}}&{{v^{\prime}(x_{1},y_{1},t_{1})}}&{{\cdots}}&{{v^{\prime}(x_{N x},y_{N y},t_{1})}}\\ {{\vdots}}&{{}}&{{\cdots}}&{{v^{\prime}(x_{N x},y_{N y},t_{2})}}&{{\cdots}}&{{v^{\prime}(x_{N x},y_{N y},t_{m})}}\\ {{\vdots}}&{{}}&{{}}&{{}}&{{\vdots}}\\ {{\vdots}}&{{}}&{{}}&{{}}&{{v^{\prime}(x_{N x},y_{N y},t_{m})}}&{{\cdots}}&{{v^{\prime}(x_{N x_{N y},t_{m}})}}\end{array}\right).$

May adding more of these into the dataset and retraining model will improve performances (?)

**Comment by lukas-blecher** [comment]
Yes, this is definitely a data problem. 

Also there was a bug in the preprocessing with matrices and multiline equations in general.
I do have a huge update planned for the end of this year that hopefully solves many of the problems right now.
