### ISSUE TITLE
Add weights please

### ISSUE THREAD

**Issue by HdVsha** [lukas-blecher/LaTeX-OCR#20]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
Missing key(s) in state_dict:

**Comment by lukas-blecher** [comment]
That looks like you have some weights downloaded.
I upgraded the model a couple of weeks ago. 
- Check if you are on the latest commit of the repository
- Make sure you have `settings/config.yaml` set as config
- Download the latest weights from the [Drive](https://drive.google.com/drive/folders/1cgmyiaT5uwQJY2pB0ngebuTcK5ivKXIb)

Tell me if that works and if not please post the full stack trace. 
Thanks!

**Comment by HdVsha** [comment]
Thanks for such fast response
Everything is up to date and I am trying to run the program with 'python gui.py'
Here is more Traceback:

/home/ramil/PycharmProjects/LaTeX-OCR/env/lib/python3.9/site-packages/albumentations/augmentations/transforms.py:868: FutureWarning: This class has been deprecated. Please use ImageCompression
  warnings.warn(
Traceback (most recent call last):
  File "/home/ramil/PycharmProjects/LaTeX-OCR/gui.py", line 274, in <module>
    ex = App(arguments)
  File "/home/ramil/PycharmProjects/LaTeX-OCR/gui.py", line 26, in __init__
    self.initModel()
  File "/home/ramil/PycharmProjects/LaTeX-OCR/gui.py", line 33, in initModel
    args, *objs = pix2tex.initialize(self.args)
  File "/home/ramil/PycharmProjects/LaTeX-OCR/pix2tex.py", line 55, in initialize
    model.load_state_dict(torch.load(args.checkpoint, map_location=args.device))
  File "/home/ramil/PycharmProjects/LaTeX-OCR/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "decoder.net.pos_emb.weight", "decoder.net.attn_layers.layers.0.0.fn.to_q.weight",
and many others

**Comment by lukas-blecher** [comment]
That is weird. What version of `x_transformers` do you have installed?
`decoder.net.pos_emb.weight` should be `decoder.net.pos_emb.emb.weight`
I think for `x_transformers`  version < 0.5.0 this was the convention.
Please try updating:
```
pip install x-transformers -U
```
If that was not the issue can you please print all missing keys from the state dict.
Also what pytorch version are you using?

**Comment by HdVsha** [comment]
I am suing torch==1.8.1 and your command seems to have solved the problem. Thanks for help!

**Comment by lukas-blecher** [comment]
No problem.
