### ISSUE TITLE
Pip doesn't install single modules of pix2tex

### ISSUE THREAD

**Issue by FrankFrank9** [lukas-blecher/LaTeX-OCR#200]
On MacOS:
<img width="291" alt="Screenshot 2022-09-28 at 07 41 27" src="https://user-images.githubusercontent.com/91851558/192696988-af68b9a1-0199-44c4-bee7-ceba94d7ff39.png">
The same error appears with all other moduli; whilst it works if calling:
 $ pip install pix2tex

**Comment by lukas-blecher** [comment]
What are you trying? The command is still `pix2tex`
if you install pix2tex[train] all you can do more is execute the `train.py` script.
```
python -m pix2tex.train --config path_to_config_file
```

**Comment by lukas-blecher** [comment]
Are you saying `pip install pix2tex[train]` doesn't work? I don't understand the problem

**Comment by lukas-blecher** [comment]
What is the error message?

**Comment by lukas-blecher** [comment]
ah it's a zsh thing
try `pip install "pix2tex[train]"
