### ISSUE TITLE
White snip-screen bug in Linux (LXQt - Lubuntu)

### ISSUE THREAD

**Issue by Nicholas-R-Sheriff** [lukas-blecher/LaTeX-OCR#206]
First of all, I would like to send a big **thank you** to the author of this special and super-useful project.

I am sorry for the possibly really dumb question, but it is unclear to me how to run the GUI from terminal in Linux. So, how to do it?
I am also trying to figure out how to manually call the GUI with the `--gnome` option, but if I understand this [commit](https://github.com/lukas-blecher/LaTeX-OCR/commit/6a94ab15571d7e2dab86e30a622cfd63b4d1f3b1) well, there has been an implementation to automatically run the GUI under gnome-screenshot.

Though, when I launch the GUI with `pix2tex --gui` or `latexocr` it runs the normal interface, which in my specific instance happens to be useless because when I click on `snip` my display **turns completely white**  - so that it is impossible to select a proper area - until I am in the screenshot environment in which you left-click and drag to draw the box for the snip to be collected and be forecast.

On the opposite, when I simply launch `gnome-screenshot` it runs as it is intended to, so it seems that the auto-call for a `--gnome` option when calling `latexocr` or `pix2tex --gui` does not work in my case. 

I read [this](https://github.com/lukas-blecher/LaTeX-OCR/issues/110), [this](https://github.com/lukas-blecher/LaTeX-OCR/pull/111), [this](https://github.com/lukas-blecher/LaTeX-OCR/pull/111/commits/5545f02cc700aedf8d9fcd51fe5e17e277f030de), and, as mentioned, [this](https://github.com/lukas-blecher/LaTeX-OCR/commit/6a94ab15571d7e2dab86e30a622cfd63b4d1f3b1).

My attempts were
1. `latexocr --gnome` ---> `pix2tex: error: unrecognized arguments: --gnome`
2. `pix2tex --gui --gnome` ||
3. `pix2tex --gnome` ||
4.  `pix2tex --gnome-screenshot` ---> `pix2tex: error: unrecognized arguments: --gnome-screenshot`
5. `latexocr --gnome-screenshot` ||
6. `pix2tex --gui --gnome-screenshot` ||
7. `pix2tex --gui -gnome` ---> `pix2tex: error: unrecognized arguments: -gnome`
8. `latexocr -gnome` ---> ||

I am using the **LXQt** Desktop Environment `v. 0.14.1` (**Lubuntu**)

```
~$    pip show pix2tex
Name: pix2tex
Version: 0.0.29
Summary: pix2tex: Using a ViT to convert images of equations into LaTeX code.
Home-page: https://github.com/lukas-blecher/LaTeX-OCR/
Author: Lukas Blecher
Author-email: luk.blecher@gmail.com
License: MIT
Location: ~/.local/lib/python3.8/site-packages
Requires: PyYAML, torch, timm, numpy, munch, einops, requests, opencv-python-headless, albumentations, Pillow, tqdm, x-transformers, pandas, transformers, tokenizers
```
```
~$    uname -a

Linux 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
```
~$    cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
~$    gnome-screenshot --version
gnome-screenshot 3.36.0
```

**_Thank you once more!_**

**Comment by Nicholas-R-Sheriff** [comment]
IMPORTANT EDIT: The issue I mentioned _**automagically** disappeared_ following a **second reboot** (the first time I tried to reboot but the problem was still there) after the installation of `pix2tex`. I don't know how to figure out how and why this all occurred, but having it reported may be useful if someone else stumbles upon it.
Sorry for having bothered you all. Keep rocking!

**Comment by lukas-blecher** [comment]
Thank you a lot for the very detailed report! 
I don't know what happened in your case. Maybe using `os.system` to call gnome-screenshot is not ideal.
Maybe a `subprocess` call would be better.
Anyways, glad it resolved itself.

**Comment by Nicholas-R-Sheriff** [comment]
Yup! But it seems to be recommended to use `subprocess.run` instead of the deprecated `os.system` and also instead of `subprocess.call` since `Python 3.5`. Don't want to seem like a _know-it-all_, I didn't know either and just found it out 15 minutes ago [here](https://hackernoon.com/calling-shell-commands-from-python-ossystem-vs-subprocess-mc253z4f).
