### ISSUE TITLE
Deficiencies in recognition

### ISSUE THREAD

**Issue by benzxiaojunjun** [lukas-blecher/LaTeX-OCR#22]
It always recognize 0 as () or O.It seems that the simpler the formula, the less likely it is to predict success.

**Comment by lukas-blecher** [comment]
Can you please share an example image?
I think it is coupled with the image size. During training I only fed the network images in the size ranges of [32, 96] and [192, 672].
I probably need to do some further finetuning with the full dataset (I thought I already did).
The complexity of the formula can be a factor but in general simpler formulae have higher the accuracy is.

**Comment by benzxiaojunjun** [comment]
![test1](https://user-images.githubusercontent.com/72971361/122032965-b234e700-ce02-11eb-960c-d412a6cc54e3.jpg)
![7](https://user-images.githubusercontent.com/72971361/122032991-b6f99b00-ce02-11eb-9efa-e9a2818d41c5.png)
![3](https://user-images.githubusercontent.com/72971361/122033009-b95bf500-ce02-11eb-9f6c-f109f37638b7.png)
Thanks a lot!

**Comment by benzxiaojunjun** [comment]
Your point is correct, I have scaled the picture down to your size, and Figure 2 does make the prediction (it didn't success before). Figure 1 is still a prediction failure, and it seems to be more than just a matter of picture size.

**Comment by lukas-blecher** [comment]
Yes, that's what I concluded as well. 
Figure 1 is also a little bit weird. What output code would you expect. I'm not aware of a bold & italic command in the math modus. `\mathbf{\mathit{...}}` does not work for me. So it probably is a font which is not in the training domain.
Figure 2 should have been resized properly by the resize network. But it seems to have failed here. I will have to train the network further.
Thanks for bringing it to my attention

**Comment by benzxiaojunjun** [comment]
I expect Figure 1 to produce the same result as Figure 2, perhaps because of font problems, where 1 is recognized as L and 0 is recognized as O. Thank you for answering my question.Have a nice day.
