### ISSUE TITLE
About the downloaded files

### ISSUE THREAD

**Issue by SuperHHzy** [lukas-blecher/LaTeX-OCR#224]
How to download image_resizer.pth and weights.pth？Can you give a link？

**Comment by lukas-blecher** [comment]
You can download them from the release page
atm the links are
https://github.com/lukas-blecher/LaTeX-OCR/releases/download/v0.0.1/weights.pth
https://github.com/lukas-blecher/LaTeX-OCR/releases/download/v0.0.1/image_resizer.pth
