### ISSUE TITLE
snip failed

### ISSUE THREAD

**Issue by lmy86263** [lukas-blecher/LaTeX-OCR#23]
I found some problems happed in the process of snip, 

> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:84: RuntimeWarning: invalid value encountered in true_divide
>   data = (data-data.min())/(data.max()-data.min())*255
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:94: RuntimeWarning: Degrees of freedom <= 0 for slice
>   if rect[..., -1].var() == 0:
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> height and width must be > 0
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:84: RuntimeWarning: invalid value encountered in true_divide
>   data = (data-data.min())/(data.max()-data.min())*255
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:94: RuntimeWarning: Degrees of freedom <= 0 for slice
>   if rect[..., -1].var() == 0:
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> height and width must be > 0
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:84: RuntimeWarning: invalid value encountered in true_divide
>   data = (data-data.min())/(data.max()-data.min())*255
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:94: RuntimeWarning: Degrees of freedom <= 0 for slice
>   if rect[..., -1].var() == 0:
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> height and width must be > 0
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:84: RuntimeWarning: invalid value encountered in true_divide
>   data = (data-data.min())/(data.max()-data.min())*255
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:94: RuntimeWarning: Degrees of freedom <= 0 for slice
>   if rect[..., -1].var() == 0:
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> height and width must be > 0
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:84: RuntimeWarning: invalid value encountered in true_divide
>   data = (data-data.min())/(data.max()-data.min())*255
> /Users/lmy86263/SourceTreeRepo/OCR-Latex/LaTeX-OCR/utils/utils.py:94: RuntimeWarning: Degrees of freedom <= 0 for slice
>   if rect[..., -1].var() == 0:
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
>   arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
> /usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
>   

  This problem leads to failure of prediction for latex.

**Comment by lukas-blecher** [comment]
Can you please share the image you were trying to predict from? So that I can reproduce the error.
I've noticed a problem as well, when there is light font on light background (or both dark).

**Comment by lmy86263** [comment]
> Can you please share the image you were trying to predict from? So that I can reproduce the error.
> I've noticed a problem as well, when there is light font on light background (or both dark).

I found a possible reason for this. I use macBook, when I snip in the retina screen, it happens all time, but when I switch to another screen(DELL), it gets better. So resolution may be the reason. 

![image](https://user-images.githubusercontent.com/10420963/122492147-d61d4600-d017-11eb-9d67-f27ceea67272.png)

**Comment by lukas-blecher** [comment]
The network does not produce the correct latex code, but it does not throw the error you posted above, when I try to predict from the image you attached. Can you verify this very image throws the error?
There definitely still are problems with too large images I'll have to sort out, but I don't think they can produce this error.
It's more likely that the bounding box detection failed in my opinion.

**Comment by lukas-blecher** [comment]
I think this is now fixed.
