### ISSUE TITLE
Unable to run latexocr

### ISSUE THREAD

**Issue by atomicsam** [lukas-blecher/LaTeX-OCR#232]
Whenever I try to run the latexocr command on linux, I get an error message stating that bash: latexocr: command not found.
I have confirmed that pix2tex was installed using pip install. How would I go about fixing this error?

**Comment by Jish2** [comment]
How did you fix it?

**Comment by atomicsam** [comment]
The reason was to do with pip3. You have to ensure that the path to your pip3 applications has been added to your environment label. This was for linux but from a little bit of searching it seems as though this could also happen to windows users. 
For linux I came across something similar to this post, and it fixed my problem. https://stackoverflow.com/questions/62822956/how-to-make-pip-install-to-path-on-linux
