### ISSUE TITLE
Only for screenshots ?

### ISSUE THREAD

**Issue by Pierre918** [lukas-blecher/LaTeX-OCR#237]
Hello, first congratulations for your ocr, it is a huge project !
But i wanted to know if it also worked with images taken with my phone for example ? (and not only with screenshots ?)

Thank you

**Comment by lukas-blecher** [comment]
This is not easy to achieve and currently not in the scope of the project.
That would require am equation detection step beforehand and a finetuning dataset which I don't have or know how to get

So, yeah sadly only screenshots
