### ISSUE TITLE
Execute from Python script?

### ISSUE THREAD

**Issue by b4rlw** [lukas-blecher/LaTeX-OCR#238]
Assuming I didn't want to use the GUI or CLI as the README suggests, is there a supported way to execute directly from a Python script?

Of course, I could use `subprocess.run` to execute the CLI from a Python script, but this seems needlessly convoluted for my intended use case.

**Comment by lukas-blecher** [comment]
Yes you can use it as a python module as well.

```python
from PIL import Image
from pix2tex.cli import LatexOCR

img = Image.open('path/to/image.png')
model = LatexOCR()
print(model(img))
```

**Comment by b4rlw** [comment]
Much obliged!
