### ISSUE TITLE
Screenshot doesn't work on Wayland?

### ISSUE THREAD

**Issue by Giovy27072** [lukas-blecher/LaTeX-OCR#249]
The screenshot doesn't work on Wayland:

![immagine](https://user-images.githubusercontent.com/73668600/225728092-0988bb79-2218-4cb8-b4f7-d33824387469.png)

When i try to take a screenshot a gray window appear.

System: Arch Linux x64
Desktop: KDE Plasma

**Comment by lukas-blecher** [comment]
Hi sorry for the late reply. Have you tried installing gnome-screenshot?

**Comment by Giovy27072** [comment]
> Hi sorry for the late reply. Have you tried installing gnome-screenshot?

Ops....Thanks

**Comment by Girolam** [comment]
Ubuntu 22.04, Wayland. After giving the command latexocr, I get the program window and if I click on "Snip" I get a gray window on one of the displays, and if I track a square with the cursor I get the error, "OSError: X get_image failed: error 8 (73, 0, 1176)".
What's the matter? 
Or. How do I get gnome-screenshot work with latexocr.
Thanks. Sorry if my questions are silly, point me in the right direction, please.

**Comment by AguiarPhys** [comment]
Similar issue/solution on Ubuntu 22.04.3 LTS: 

Gray screen when you try to take a snip and error code:

```
OSError: Pillow was built without XCB support
Aborted (core dumped)
```
Solution: 

Install gnome-screenshot package:
```
sudo apt install gnome-screenshot
```
Did the trick!
