### ISSUE TITLE
pix2tex api

### ISSUE THREAD

**Issue by Boluex** [lukas-blecher/LaTeX-OCR#259]
please how can i turn python -m pix2tex .api.run to an actual api to use in my project and deploy it.......or how can i use it in my python script for deployment............Nice project (pix2tex) tho

**Comment by lukas-blecher** [comment]
What do you mean "actual api"?

Usage from python (#238):
```python
from PIL import Image
from pix2tex.cli import LatexOCR

img = Image.open('path/to/image.png')
model = LatexOCR()
print(model(img))
```

**Comment by Boluex** [comment]
it didn't work 

the code

model=LatexOCR()
open_image=Image.open(r"/home/deji/Downloads/integration.png")
image = Image.open(open_image)
print_output=model(image)
expr = sympify(print_output)
print(expr)


the error  


Projects/pythonProject/msg.py
Traceback (most recent call last):
  File "/home/deji/Desktop/deji/PycharmProjects/pythonProject/msg.py", line 186, in <module>
    image = Image.open(open_image)
  File "/home/deji/.local/lib/python3.10/site-packages/PIL/Image.py", line 3236, in open
    prefix = fp.read(16)
  File "/home/deji/.local/lib/python3.10/site-packages/PIL/Image.py", line 529, in __getattr__
    raise AttributeError(name)
AttributeError: read

**Comment by lukas-blecher** [comment]
Because you tried to open and PIL image.
change `open_image=Image.open(r"/home/deji/Downloads/integration.png")` to `open_image=r"/home/deji/Downloads/integration.png"`
