### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ltw321** [lukas-blecher/LaTeX-OCR#267]

**Comment by lukas-blecher** [comment]
Can you give me some more context please? Which model load fails?
From a quick google search it looks like the model checkpoint you have is corrupt. Can you try to re-download the checkpoint files?

**Comment by ltw321** [comment]
> Can you give me some more context please? Which model load fails? From a quick google search it looks like the model checkpoint you have is corrupt. Can you try to re-download the checkpoint files?

I've solved the above problem, go to F:anaconda\Libsite-packages\pix2tex\model\checkpoints to find "image_resizer.pth "and "weights.pth "to delete and re-execute" python -m pix2tex.api.run "on it
