### ISSUE TITLE
Hugging space is down

### ISSUE THREAD

**Issue by Kreijstal** [lukas-blecher/LaTeX-OCR#269]
Your hugging space has not been up in weeks/months, what's up with that?

**Comment by lukas-blecher** [comment]
It's working for me. There were some issues at some point, but I thought I resolved them.

Please tell me if it's still not working for you

https://huggingface.co/spaces/lukbl/LaTeX-OCR

**Comment by Kreijstal** [comment]
Oh okay, it is now up, sorry.
