### ISSUE TITLE
PDF to Latex conversion

### ISSUE THREAD

**Issue by Cram3r95** [lukas-blecher/LaTeX-OCR#270]
Hi,

This is a fantastic work. I have several questions:

1. I am trying to process two equations in the same image:

![imagen](https://user-images.githubusercontent.com/15740838/234326241-1dcc99df-7fbe-49a4-8a1e-7ca902a3e721.png)

But the model is only able to (perfectly) process the first one, not both:

![imagen](https://user-images.githubusercontent.com/15740838/234326437-ff52aa00-8950-4031-af3c-ba0930e2c117.png)

Do you know why? At this moment, is it required to put a single equation per picture?

On the other hand, would this work be easily extended to process a whole PDF to Latex format? For example, if I want to get the following Latex code:

![imagen](https://user-images.githubusercontent.com/15740838/234326793-b50b8d60-820b-4675-a7b8-51f3b8159a73.png)

Best wishes and again, amazing work!

**Comment by lukas-blecher** [comment]
Hi Carlos,

1. multi-line equations are known to be hard for the model. This is mostly due to a bug in the dataset generation (#159). I think it's partly fixed now but I would need to retrain the model, which I can't do at the moment. So yeah, right now it's best to parse the equations separately.
2. Regarding PDF to Latex, I've been working on that. I'll release the project next week or so :)
 <details>
  <summary>Preview</summary>
  
 ```tex
 expected cumulative reward. A MDP is a tuple \((\mathbf{S},\mathbf{A},\mathbf{P},\mathbf{R},\gamma)\), where \(\mathbf{S}\) is a finite set of states, \(\mathbf{A}\) is a finite set of actions, \(\mathbf{P}\) is a state transition probability matrix, \(P_{ss^{\prime}}^{a}=\mathbb{P}\big{[}S_{t+1}=s^{\prime}\mid S_{t}=s,A_{t}=a\big{]}\), \(\mathbf{R}\) is a reward function, \(R_{s}^{a}=\mathbb{E}[R_{t+1}\mid S_{t}=s,A_{t}=a]\), and \(\gamma\) is a discount factor. To find the best decision process over all policies, the optimal state-value function \(v_{\star}(s)\) and the optimal action-value function \(q_{\star}(s,a)\) can be calculated as

 \[v_{\star}(s)=\max_{a}\left[R_{s}^{a}+\gamma\sum_{s^{\prime}\in A }P_{ss^{\prime}}^{a}v_{\star}\left(s^{\prime}\right)\right],\] \[q_{\star}(s,a)=R_{s}^{a}+\gamma\sum_{s^{\prime}\in A}P_{ss^{ \prime}}^{a}\max_{a^{\prime}}q_{\star}\left(s^{\prime},a^{\prime}\right). \tag{5}\]

 Using MDP, the RL-based methods can be classified as Inverse Reinforcement Learning (IRL) methods, Generative Adversarial Imitation Learning (GAIL) methods, and Deep IRL (DIRL) methods, which will be discussed below.
 ```
  
 </details>

**Comment by mrpositron** [comment]
I am looking forward to pdf2tex conversion!

As of now I have implemented simple project that extracts equation from the research paper and converts them to tex articles (using LaTeX-OCR). 

Check it out: https://github.com/mrpositron/paper2tex

**Comment by Cram3r95** [comment]
@mrpositron very well done my friend! Is it possible to convert the whole PDF to .tex format? Including images, text and equations. This is a really good contribution, same as work proposed by @lukas-blecher to the community!

**Comment by mrpositron** [comment]
Thanks!

Ultimately I also want to convert pdf to tex. But, as of now it is just converting equations to .tex format.

**Comment by Lev-Stambler** [comment]
> 

Hi Lukas, I was wondering if there was any follow up on this? Would be very interested!

**Comment by lukas-blecher** [comment]
yes, sorry for the delay. internal stuff blocking this. At most 2 weeks from now

**Comment by Lev-Stambler** [comment]
> 

Fantastic. Thank you!

**Comment by Lev-Stambler** [comment]
> yes, sorry for the delay. internal stuff blocking this. At most 2 weeks from now

Just following up again!

**Comment by lukas-blecher** [comment]
Very sorry for the delay. It was out of my hands. But now it is finally ready 🎉
https://github.com/facebookresearch/nougat
