### ISSUE TITLE
gui does not show the original text

### ISSUE THREAD

**Issue by j4y33** [lukas-blecher/LaTeX-OCR#28]
Hey guys, 

thanks for working on this, its a cool project. I have installed it and am using the GUI on win10. Here is what i see: 

![Unbenannt](https://user-images.githubusercontent.com/28354613/127500128-86707955-d73b-4276-8e72-774335b9f179.PNG)

There is no upper part of the GUI, perhaps its just the copy of the screenshot so its nothing, but just asking if this might impact the functionality.

Finally I would like to know, how can I retranslate the LATEX OCR: 

$\scriptstyle\pi(\infty)\;=\;1\times1$ 

from 

![function](https://user-images.githubusercontent.com/28354613/127500557-43706048-42d9-447c-a74f-36e9e2878d7a.PNG)

back into readable format. 

Thanks!

**Comment by lukas-blecher** [comment]
Hello, thanks for your interest in the project.

I don't know why the upper part of the GUI won't show up for you. I would recommend to reinstall the PyQt modules, especially PyQtWebEngine:
```shell
pip install -U PyQt5 PyQtWebEngine
```
In the upper part the predicted LaTeX code will be rendered using MathJax, so there is no performance impact.

For your second question I'm not sure what you mean. Do you want to convert the predicted Latex code into unicode characters? Could you elaborate on that please?

**Comment by j4y33** [comment]
Hi 

Thank you for the swift answer. First question is solved, donnow whats the problem but since its just in the gui and has no performance impacts it does not bother me. 

Second question was somewhat stupid. I meant how to render the LaTex prediction back to the formula. Now I used Katex, works fine! 

I also have a question regarding the training, is it right to post it here? 

Thanks, cheers
Julian

**Comment by lukas-blecher** [comment]
So the first two questions are related. The rendering is what the upper window was supposed to do.
Have you tried to reinstall the modules? 

Regarding the training question you can  open a new issue or head over to the [discussions](https://github.com/lukas-blecher/LaTeX-OCR/discussions).
