### ISSUE TITLE
pdfs to latex

### ISSUE THREAD

**Issue by pkozlows** [lukas-blecher/LaTeX-OCR#362]
I have a fine motor impairment, so being able to convert assigned problem sets that are in PDF into LaTeX code using OCR technology would be helpful. I tried using Mathpix, but after converting a number of documents for free, you have to subscribe. Would this software enable one to efficiently convert a long PDF document into LaTeX code like Mathpix can? I looked over the readme, but it seems like you can only use this tool if you manually take screenshots of the PDF?

**Comment by lukas-blecher** [comment]
You can check if nougat works for you: https://github.com/facebookresearch/nougat
