### ISSUE TITLE
Issue with Qt6 on macOS: am I missing something?

### ISSUE THREAD

**Issue by godisopensource** [lukas-blecher/LaTeX-OCR#363]
Hi there,
First of all, thanks for your hard work! This project looks awesome.
I tried to install it on macOS using a virtual environment with conda. I installed it using pip3 inside this virtual environment and installed all the packages required to work, including `PyQt6` and `PyQt6-WebEngine`, but when executing `latexocr` in the terminal, it gives the following error:

```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      latexocr
```

Is there something I missed? Thanks for your help.

**Comment by jiachuac** [comment]
Hi @godisopensource, I encountered the same problem. As you closed this issue, may I ask how your resolved it? Thanks a lot!
