### ISSUE TITLE
AttributeError: Can't get attribute 'Im2LatexDataset' on <module '__main__'>

### ISSUE THREAD

**Issue by jobinkv** [lukas-blecher/LaTeX-OCR#37]
During the training, I am getting the following error message.

`LaTeX-OCR/dataset/dataset.py", line 195, in load
    x = pickle.load(file)
AttributeError: Can't get attribute 'Im2LatexDataset' on <module '__main__'>`

Tanks in advance.

**Comment by lukas-blecher** [comment]
Sorry for the late reply. Thanks for bringing it to my attention.
I will try to deal with it in the very near future.

**Comment by lukas-blecher** [comment]
I was not able to reproduce the issue. Can you please describe under which circumstances the error occurred?
Thanks
