### ISSUE TITLE
)can't snip outside window (i3-wm)

### ISSUE THREAD

**Issue by jakob1379** [lukas-blecher/LaTeX-OCR#40]
I just found your great tool and it seems that the way you capture in a windows does not allow for tiling managers like i3-wm. The snipping seems to open a separate windows instead of creating a layer on top of all windows
![pix2tex](https://user-images.githubusercontent.com/17257805/136201599-b51d275f-c229-4fa5-b41b-ffefa2b3114b.png)
.

**Comment by lukas-blecher** [comment]
Hi, thanks for trying out the project.
I don't know what goes wrong here and I have no idea how to fix it.
Maybe you can find a workaround by using a working snipping tool and just us the pix2tex.py non-gui version.

**Comment by lukas-blecher** [comment]
should be fixed now with `gnome-screenshot` and flag `--gnome` thanks to #111
