### ISSUE TITLE
how to ocr low width latex image

### ISSUE THREAD

**Issue by daassh** [lukas-blecher/LaTeX-OCR#42]
![0123](https://user-images.githubusercontent.com/13551272/137657408-b70de348-87d1-4d65-9227-a00733b4ef79.png)
![0123-result](https://user-images.githubusercontent.com/13551272/137657525-505ae9cb-fc2d-4d24-9d8d-e91d1281ee9b.png)

If image width is too low, the ocr result will useless.

I have try to reduce patch_size to 8, but the error occured:
`Exception has occurred: RuntimeError
The size of tensor a (33) must match the size of tensor b (129) at non-singleton dimension 1
  File "F:\code\LaTeX-OCR\models.py", line 81, in forward_features
    x += self.pos_embed[:, pos_emb_ind]
  File "F:\code\LaTeX-OCR\train.py", line 48, in train
    encoded = encoder(im.to(device))
  File "F:\code\LaTeX-OCR\train.py", line 88, in <module>
    train(args)`

I have struggle this issue several days, Please tell me what can I do for this situation.

Thank you very much!

**Comment by lukas-blecher** [comment]
Don't change the patch size. It's fixed for this trained model.
And yes the problem you are referring to is a there. I also know why it happens and it was a stupid mistake by me when I trained the model. 
I've explained it in another issue as follows
> That is due to a mistake during training where I ommited small images from the dataset. In practice that means only images with width >96px work as expected (if I recall correctly). I'm sure if you try with somewhat larger images the result will be as expected.

I hope you can type out these small images yourself until I retrain the model though I sadly don't have the resources currently.
