### ISSUE TITLE
Munch attribute error

### ISSUE THREAD

**Issue by roongta-shrey** [lukas-blecher/LaTeX-OCR#51]
![error](https://user-images.githubusercontent.com/20886319/140260167-8d70fba7-face-4227-b5a4-d4679de9e239.PNG)

I get the above error when trying to run pix2tex.py. How can I resolve this? I am running on Windows 10.

**Comment by lukas-blecher** [comment]
Thanks for opening this issue. It should be resolved now.
Please pull the changes and try again. If it still doesn't work reopen the issue.

**Comment by roongta-shrey** [comment]
Thank you so much!! It's working now. Thank you for your amazing work :)

**Comment by lukas-blecher** [comment]
Happy to help. 
Thanks again for opening the issue.
