### ISSUE TITLE
Runtime error while running

### ISSUE THREAD

**Issue by pritam-dey3** [lukas-blecher/LaTeX-OCR#55]
I am getting this following error: ```RuntimeError: Error(s) in loading state_dict for ResNetV2:
        size mismatch for head.fc.weight: copying a param with shape torch.Size([21, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([22, 1024, 1, 1]).
        size mismatch for head.fc.bias: copying a param with shape torch.Size([21]) from checkpoint, the shape in current model is torch.Size([22])```. I don't really know how to resolve this issue, please help.

**Comment by lukas-blecher** [comment]
Hi, I guess you have not pulled the most recent commit? I did introduce some breaking changes to the image resizing network and updated the weights in the github release.
Make sure you are on fadb042 and try again please.

**Comment by pritam-dey3** [comment]
Thanks. I pulled the recent updates and it is working fine now.
