### ISSUE TITLE
gui.py cannot capture screen in the second monitor

### ISSUE THREAD

**Issue by liu-jun-yan** [lukas-blecher/LaTeX-OCR#57]
Hi, thank you for the excellent work. I meet some problems when using the gui. I am using _**Ubuntu20.04**_ with a _**kde**_ desktop. After running the screen snip(button or alt+s), I can only start the area selection in the main monitor and the opacity only changes in the main monitor. If I press my mouse in the main screen and drag it to the second screen, the program can accurately select the area but the selected rectangle only shows the main screen part. I can not select area if I firstly press my mouse in the second screen.
When using the "gui.py" script, I slightly modify it and I'm quite sure that these changes are not related with this problem. Anyway, here are the changes that I made. The ImageGrab from PIL keep throwing errors so I change `from PIL import ImageGrab` to `import pyscreenshot as ImageGrab`. I also remove the `all_screen` parameter in  line 252: `img = ImageGrab.grab(bbox=(x1, y1, x2, y2), all_screens=True)` since this parameter is only available in Windows.

**Comment by lukas-blecher** [comment]
Hi, thanks for opening the issue.
You are right, PIL does not support multiple monitors in linux. Did `pyscreenshot` end up working? Are you able to grab all monitors with the library?

If not, can you please follow these steps:
1. Install [mss](https://github.com/BoboTiG/python-mss): `pip install ms`
2. run the following script
```python
import mss
with mss.mss() as sct:
    sct.shot(mon=-1, output='fullscreen.png')
```
3. It should generate a file `fullscreen.png` in your current working directory. Can you tell me if all your screens are visible in the picture?

If so I might be able to rewrite the screen grabbing code.

**Comment by liu-jun-yan** [comment]
Thanks for your reply. Both `pyscreenshot` and `mss` can get grab all monitors.

**Comment by lukas-blecher** [comment]
Ok thank you, I think I understand now what you mean.
It won't be easy for me to debug because my Linux doesn't like additional monitors. 
I will see when I'll get around to fixing it.
Of course I'd be happy for some help if you are interested :)

**Comment by lukas-blecher** [comment]
should be fixed now with `gnome-screenshot` and flag `--gnome` thanks to #111
