### ISSUE TITLE
Model fails for a simple tex 

### ISSUE THREAD

**Issue by wklm** [lukas-blecher/LaTeX-OCR#59]
Hi, 

it's a great project, many thanks for it! The model needs some work though, I found it failing for relatively simple examples like this one: $\mathcal{X} \times \Theta \to \overbar{R}$ spitting out very different results in consecutive prediction attempts. Fundamentally this issue could be solved by the introduction of confidence thresholds... 

Cheers,
Wojtek

**Comment by lukas-blecher** [comment]
I think this can only be solved by more training data.

**Comment by lukas-blecher** [comment]
As it turns out it was another problem which is fixed now in #119 
![image](https://user-images.githubusercontent.com/55287601/163173775-c76d3bf9-5726-460f-a006-4abd9b72ae18.png)
returns now `X\times\Theta\rightarrow\bar{R}`
