### ISSUE TITLE
ValueError: Expected positive integer steps_per_epoch, but got 0

### ISSUE THREAD

**Issue by Wyukang** [lukas-blecher/LaTeX-OCR#61]
Hi, I follow the README and I have this error while training.
Is there any solution for this error? 
I appreciate your help! I'm excited to try out your code
<img width="968" alt="截圖 2021-12-16 上午11 01 22" src="https://user-images.githubusercontent.com/88665343/146301193-2b3fcaa5-95ed-4a3d-98cd-72f1c5980f7f.png">
.

**Comment by lukas-blecher** [comment]
looks like the dataloader doesn't contain any data. You might need to change the path to the pickle files in the `config.yaml` file.
Also I just updated this exact line in e3717e5. 
If you choose to use the new verison, note that the main change happened in the config file.

**Comment by Wyukang** [comment]
Thanks for your reply, I am a newbie.
I have confirmed that my pickle files path is correct.
I used the new version and got another error. The picture is below.
<img width="930" alt="截圖 2021-12-17 下午3 23 20" src="https://user-images.githubusercontent.com/88665343/146506672-33371b4f-6cce-469c-a03c-fccca4c10d45.png">

**Comment by lukas-blecher** [comment]
Sorry, that was my mistake. I deleted one line too much.

**Comment by Wyukang** [comment]
Dear author:
Sorry to interrupt you again.

When I was doing model training, this error interrupted the process. Where can I find the "invalid filename characters" that caused this problem? 
This error was encountered several times when the EPOCH was 19, seems like a new wandb bug here related to filename characters.
I did not find any help that was useful to me from the Internet. How can I fix it?

Thank you in advance
![圖片1](https://user-images.githubusercontent.com/88665343/147454822-f2bddba8-0284-4c94-a8be-129b20afe684.png)
.

**Comment by lukas-blecher** [comment]
Sorry but I can't help you with that one. Never seen this error before
