### ISSUE TITLE
training time and equipment

### ISSUE THREAD

**Issue by QzzIsCoding** [lukas-blecher/LaTeX-OCR#62]
Hi, thanks for your sharing code.  I want to use this dataset to train a similar model. So I'd like to know how long your model has been trained and what kind of machine did you use?

**Comment by lukas-blecher** [comment]
Nice to hear. I haven't yet set up a dataset license yet. Will have to find a way to add it later (probably [ODbL](https://opendatacommons.org/licenses/odbl/summary/))
I've trained for around 50 epochs on a consumer GPU with 12GB vRAM (2080Ti if I recall correctely)
