### ISSUE TITLE
what is the -tokenizer path_to_tokenizer   

### ISSUE THREAD

**Issue by aspnetcs** [lukas-blecher/LaTeX-OCR#63]
what is the -tokenizer path_to_tokenizer   
python dataset/dataset.py --equations path_to_textfile --images path_to_images --tokenizer path_to_tokenizer --out dataset.pkl

**Comment by lukas-blecher** [comment]
By default it is `dataset/tokenizer.json`. Sorry if that was unclear. I will add a note in the README.
The file is already in the repository. If you want to create your own tokenizer for your own dataset you will first need to run
```
python dataset/dataset.py --equations path_to_textfile --vocab-size 8000  --tokenizer path_to_tokenizer --out tokenizer.json
```

**Comment by aspnetcs** [comment]
Thank you very much 













--




At 2021-12-19 19:50:30, "Lukas Blecher" ***@***.***> wrote:

By default it is dataset/tokenizer.json. Sorry if that was unclear. I will add a note in the README.
The file is already in the repository. If you want to create your own tokenizer for your own dataset you will first need to run

python dataset/dataset.py --equations path_to_textfile --vocab-size 8000  --tokenizer path_to_tokenizer --out tokenizer.json


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
