### ISSUE TITLE
how to get the data ?

### ISSUE THREAD

**Issue by aspnetcs** [lukas-blecher/LaTeX-OCR#64]
Data
We need paired data for the network to learn. Luckily there is a lot of LaTeX code on the internet, e.g. wikipedia, arXiv. We also use the formulae from the im2latex-100k dataset. All of it can be found here.

where is the wikipedia data ? how to use it ?
where is the arXiv data ? how to use it ?

**Comment by lukas-blecher** [comment]
I've compiled them into one dataset which can be downloaded from Google Drive: https://drive.google.com/drive/folders/13CA4vAmOmD_I_dSbvLp-Lf0s6KiaNfuO
What do you mean by how to use it? Is the documentation not clear? Which part should I clarify?
