### ISSUE TITLE
How to divide the crohme data set（CROHME.zip is in your google driver） into training data sets, validation data sets, and test data sets for testing ?

### ISSUE THREAD

**Issue by aspnetcs** [lukas-blecher/LaTeX-OCR#65]
How to divide the crohme data set（CROHME.zip is in your google driver） into training data sets, validation data sets, and test data sets for testing ?

**Comment by lukas-blecher** [comment]
Just randomly split up the files into three directories. I've done it like [this](https://stackoverflow.com/questions/14033129/how-to-move-a-given-number-of-random-files-on-unix-linux-os).
