### ISSUE TITLE
generate the cromhe tokenizer.json  ,error,how to fix it ?

### ISSUE THREAD

**Issue by aspnetcs** [lukas-blecher/LaTeX-OCR#66]
(tf_1.12) root@f15b165683e6:/home/code/LaTeX-OCR# python dataset/dataset.py --equations latex-ocr-data/crohme/CROHME_math.txt --vocab-size 8000 --out crohme-tokenizer.json
Generate tokenizer
Traceback (most recent call last):
  File "dataset/dataset.py", line 244, in <module>
    generate_tokenizer(args.equations, args.out, args.vocab_size)
  File "dataset/dataset.py", line 228, in generate_tokenizer
    trainer = BpeTrainer(special_tokens=["[PAD]", "[BOS]", "[EOS]"], vocab_size=vocab_size, show_progress=True)
TypeError: 'str' object cannot be interpreted as an integer
(tf_1.12) root@f15b165683e6:/home/code/LaTeX-OCR# 
how to fix it ?

**Comment by lukas-blecher** [comment]
Hm maybe its a version conflict. Can you confirm your `tokenizers` version is `0.9.4`?

**Comment by Agha-Muqarib** [comment]
I've got this same error. The tokenizer version is 0.9.4 as well. Any idea on how to fx this one?

**Comment by lukas-blecher** [comment]
There was a mistake as explained in #81. You need to pull the changes I've made.

**Comment by aspnetcs** [comment]
there is no error in windows。you can use windows operating system













--




At 2022-01-23 22:12:48, "Agha Muqarib Khan" ***@***.***> wrote:

I've got this same error. The tokenizer version is 0.9.4 as well. Any idea on how to fx this one?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukas-blecher** [comment]
The loss is the is provided by the decoder during training time.

https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104

**Comment by aspnetcs** [comment]
Can other forms of loss function be used?
How to make a learning rate graph with https://wandb.ai/  ？


The adamw optimization algorithm is used by default. Can it be replaced by the SGD optimization algorithm? If so, how?













--




At 2022-03-10 21:58:46, "Lukas Blecher" ***@***.***> wrote:

The loss is the is provided by the decoder during training time.

https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aspnetcs** [comment]
where is the loss in your LaTeX-OCR project(lukas-blecher/LaTeX-OCR  https://github.com/lukas-blecher/LaTeX-OCR)
Is this the one below? It feels like they are not the same project

https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104










--




At 2022-03-10 21:58:46, "Lukas Blecher" ***@***.***> wrote:

The loss is the is provided by the decoder during training time.

https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukas-blecher** [comment]
### New optimizer
Replace the line
https://github.com/lukas-blecher/LaTeX-OCR/blob/fd271d25f9aaac6225dfd3e6460a2cfc07ebca96/train.py#L38
with 
```python
    opt = optim.SGD(model.parameters(), args.lr)
```
You can add the current lr to the logging dict. Here for StepLR scheduler
```python
wandb.log({'train/loss': loss.item(),'train/lr': scheduler.get_last_lr()})
```

### Loss
> where is the loss in your LaTeX-OCR project(lukas-blecher/LaTeX-OCR  https://github.com/lukas-blecher/LaTeX-OCR)
Is this the one below? It feels like they are not the same project
> https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104

Yes it is the loss I'm using. `x-transformers` is a dependency

**Comment by aspnetcs** [comment]
wandb.log({'train/loss': loss.item(),'train/lr': scheduler.get_last_lr()})Which file should this sentence be placed in the project?













--




At 2022-03-12 00:10:31, "Lukas Blecher" ***@***.***> wrote:

New optimizer

Replace the line
https://github.com/lukas-blecher/LaTeX-OCR/blob/fd271d25f9aaac6225dfd3e6460a2cfc07ebca96/train.py#L38
with

opt=optim.SGD(model.parameters(), args.lr)

You can add the current lr to the logging dict. Here for StepLR scheduler

wandb.log({'train/loss': loss.item(),'train/lr': scheduler.get_last_lr()})
Loss

where is the loss in your LaTeX-OCR project(lukas-blecher/LaTeX-OCR https://github.com/lukas-blecher/LaTeX-OCR)
Is this the one below? It feels like they are not the same project
https://github.com/lucidrains/x-transformers/blob/856c869faf08bb91976624d5ba01e73851b21dcf/x_transformers/autoregressive_wrapper.py#L91-L104

Yes it is the loss I'm using. x-transformers is a dependency

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukas-blecher** [comment]
> wandb.log({'train/loss': loss.item(),'train/lr': scheduler.get_last_lr()})Which file should this sentence be placed in the project?

https://github.com/lukas-blecher/LaTeX-OCR/blob/fd271d25f9aaac6225dfd3e6460a2cfc07ebca96/train.py#L56
