### ISSUE TITLE
Hello, author. Thank you for your open source. Unfortunately, in the course of the experiment, I found that only train TXT, test and val do not have corresponding txt files? I'd like to ask where this document is

### ISSUE THREAD

**Issue by gittjob** [lukas-blecher/LaTeX-OCR#68]
![image](https://user-images.githubusercontent.com/82756842/147207381-11a83245-ba74-43ff-b720-ab5670fb55d8.png)

**Comment by lukas-blecher** [comment]
`math.txt` contains the ground truth for all splits. The corresponding lines are separated by the image file names.
You only have to change the `images` and `out` attribute when creating the pickle files

**Comment by gittjob** [comment]
Thank u,You are my Savior.
