### ISSUE TITLE
Code understanding

### ISSUE THREAD

**Issue by Lakhan-123** [lukas-blecher/LaTeX-OCR#69]
I want to understand the whole code please direct me where i can find help

**Comment by lukas-blecher** [comment]
I don't know how to help you with that. If you have a specific question you can ask me but the whole code base?

**Comment by Lakhan-123** [comment]
thank you, Lukas, can you tell me the preferred environment of this project because after installing all the requirements the terminal still giving me the error

**Comment by lukas-blecher** [comment]
Which error? Which command did you execute?
Can you show me the output of `pip list`?

**Comment by Lakhan-123** [comment]
hey lukas, at first model gave the better results for the input images but
after 5 or 8 times running the program its not giving expected results and
not even extracting the equation from image.
But I also had scanned an image containing two different equations may be
thats why model is acting weird.
You can see the attached image.

**Comment by Lakhan-123** [comment]
And also can you tell me which of these files and folders contains the
algorithm which extracting the equation from image and like which program
making bounding boxes around text(characters) and which program making
latex code using these information?
Thank You..

**Comment by lukas-blecher** [comment]
Yes, two different equations are known to produce bad results (The image did not make it through to github)

1. Extraction of the information happens in the ViT [here](https://github.com/lukas-blecher/LaTeX-OCR/blob/97c9644e776862234f71c0913b9b2a4e8da2fc15/models.py#L71)
2. This information is presented to a decoder [here](https://github.com/lukas-blecher/LaTeX-OCR/blob/97c9644e776862234f71c0913b9b2a4e8da2fc15/models.py#L19), which creates a probability distribution over all tokens and chooses the most likely one.
3. Tokens are translated back to readable text using the tokenizer [here](https://github.com/lukas-blecher/LaTeX-OCR/blob/97c9644e776862234f71c0913b9b2a4e8da2fc15/utils/utils.py#L66)
4. Images are cropped and preprocessed [here](https://github.com/lukas-blecher/LaTeX-OCR/blob/97c9644e776862234f71c0913b9b2a4e8da2fc15/utils/utils.py#L73)

**Comment by Lakhan-123** [comment]
THANKS MAN..

**Comment by Lakhan-123** [comment]
hey Lukas, please guide me from where should I start to understand the code
step by step and do I need to learn DL and ML for that..

**Comment by lukas-blecher** [comment]
Well it is a DL application so if you want to understand whats happening, you need some understanding of ML.
Read the papers I referenced at the bottom of the README. For that check out this [notebook](https://github.com/bentrevett/pytorch-seq2seq/blob/master/6%20-%20Attention%20is%20All%20You%20Need.ipynb).
In the code you can see, I mostly rely on third party packages, where the actual computation is happening. So check out the relevant code in the `timm` and `x-transformers` packages.
I don't know what else I can tell you.

**Comment by Lakhan-123** [comment]
Thanks, I'll check it out.
You told me a lot Thank you..

**Comment by Lakhan-123** [comment]
lukas... What exactly katex(js files) doing in model?? And is this a model
with encoder/decoder architecture?

**Comment by lukas-blecher** [comment]
The katex files are there only for preprocessing the latex equation. Because many different expressions can be rendered to the same image. This step makes it easier for the model to converge later on. 
The code is adapted from https://github.com/harvardnlp/im2markup
This step makes it easier for the model to converge later on. 

Yes, the model consists of an encoder and a decoder. 
The encoder is a vision transformer without the last classification layer and the decoder is a transformer decoder.
