### ISSUE TITLE
Return unbalanced latex equations

### ISSUE THREAD

**Issue by GopinathCool** [lukas-blecher/LaTeX-OCR#7]
I tested with lot of images, but for most of the images it results in an unbalanced latex equation, do you have any idea to resolve it?
I also attached the produced latex equation and image for reference.

$$U_{s2A_{-}k}=\bar{\cal B}_{s}_{s\bar{G}^{+}}\cdot\bar{Y}_{s2A_{-}\bar{k}}+\bar{\cal B}_{r}\frac{\displaystyle\frac{\displaystyle\cal L}_{m}^{2}}{\displaystyle\frac{\displaystyle\cal L}{\displaystyle\frac{\displaystyle\cal E}_{m}}{\displaystyle\cal P}_{s}\cdot\bar{\cal A}_{2}\cdot\bar{\cal I}_{s22}\cdot\bar{Y}_{s2\bar{\cal B}_{-}\bar{\cal F}_{s}}{\displaystyle\cal E}_{s2\bar{\cal F}_{-}\displaystyle\cal A}^{-}\left(\frac{\displaystyle\frac{\displaystyle\frac{\displaystyle\cal E}_{m}\cdot\bar{\cal S}_{s}}{\displaystyle\cal E}_{s}^{2}}\right)\cdot\bar{\mathrm Y}_{s4\bar{\cal B}_{s2}\cdot\bar{\cal A}_{s2}\displaystyle\cal E_{s}\bar{\cal F}_{s}\right\},$$
![patent_8_60](https://user-images.githubusercontent.com/31401733/116654873-a652aa00-a9a7-11eb-80b3-83d8976e5c3a.png)

**Comment by lukas-blecher** [comment]
Hi, thank you for your interest in the project.
I can see 2 or 3 problems with the Image:
1. The image is a bitmask (no gradient from black to white). The network has not trained on bitmask images.
2. Underscores are underrepresented in the training set
3. I don't recognize the font. Maybe the network has problems with that

When I rerender the image:
![image](https://user-images.githubusercontent.com/55287601/116660739-be203300-a993-11eb-8193-4fb735897a78.png)
The model returns
```
U_{s t a k.\,k}=R_{s G2}\cdot Y_{s a A.\,k}+R_{r}\frac{L_{m}^{2}}{L_{r}^{2}}\cdot Y_{s1A F_{2}\,k}-\omega_{\psi s}\cdot\sigma_{2}L_{s2}\cdot Y_{s b P\,k}-\omega_{\psi s}\cdot\sigma_{2}L_{s a b F\,k}\cdot Y_{s1B F\,k}-\left(\frac{L_{m}\cdot R_{r}}{L_{r}^{2}}\right)\cdot\Psi_{r A k}
```
![image](https://user-images.githubusercontent.com/55287601/116660935-fd4e8400-a993-11eb-94ad-ea33894e0b48.png)
Which is not unbalanced and is fairly close to the input image. 

I will take note and also train on a small subset of bitmask images. That should sort it out for the most part but will take some time.

**Comment by GopinathCool** [comment]
Thanks for your answer, the latex you have provided well balanced and also close to the image. But just one question how would be able to achieve that, do I need to update any part of the code?
It will be really helpful, if you could update and provide your model to handle bitmask images also.

**Comment by GopinathCool** [comment]
I have seen your recent commit, do I need to retrain the model with your formulae.zip images to handle bitmask images?

**Comment by lukas-blecher** [comment]
I have trained a new model (slightly different architecture) with the new commit `005648b`.
The font is still hard to read for the model but it works. If you have problems try to change the temperature.
