### ISSUE TITLE
fail during installation

### ISSUE THREAD

**Issue by jave** [lukas-blecher/LaTeX-OCR#72]
I'm trying to install on Fedora 34. I made a venv to contain the installation.
Fedora has Python 3.9.9

 1075  git clone https://github.com/lukas-blecher/LaTeX-OCR.git
 1076  cd LaTeX-OCR/
 1078  python3 -m venv ltx-ocr
 1080  . ./ltx-ocr/bin/activate
 1082  pip install -r requirements.txt

error:
Collecting tqdm>=4.47.0
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting munch>=2.5.0
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting torchvision>=0.8.1
  Using cached torchvision-0.11.2-cp39-cp39-manylinux1_x86_64.whl (23.2 MB)
Collecting opencv_python_headless>=4.1.1.26
  Using cached opencv_python_headless-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (47.7 MB)
Collecting requests>=2.22.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting einops>=0.3.0
  Using cached einops-0.3.2-py3-none-any.whl (25 kB)
Collecting chardet>=3.0.4
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting x_transformers==0.15.0
  Using cached x_transformers-0.15.0-py3-none-any.whl (11 kB)
Collecting torch>=1.7.0
  Using cached torch-1.10.1-cp39-cp39-manylinux1_x86_64.whl (881.9 MB)
Collecting imagesize>=1.2.0
  Using cached imagesize-1.3.0-py2.py3-none-any.whl (5.2 kB)
Collecting transformers>=4.2.2
  Using cached transformers-4.15.0-py3-none-any.whl (3.4 MB)
Collecting tokenizers==0.9.4
  Using cached tokenizers-0.9.4-cp39-cp39-manylinux2010_x86_64.whl (2.9 MB)
Collecting numpy>=1.19.5
  Using cached numpy-1.21.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting Pillow>=8.1.0
  Using cached Pillow-8.4.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting PyYAML>=5.4.1
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
Collecting torchtext>=0.6.0
  Using cached torchtext-0.11.1-cp39-cp39-manylinux1_x86_64.whl (8.0 MB)
Collecting albumentations>=0.5.2
  Using cached albumentations-1.1.0-py3-none-any.whl (102 kB)
Collecting pandas>=1.0.0
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting timm
  Using cached timm-0.4.12-py3-none-any.whl (376 kB)
Collecting python-Levenshtein>=0.12.2
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Collecting PyQtWebEngine
  Using cached PyQtWebEngine-5.15.5-cp36-abi3-manylinux1_x86_64.whl (228 kB)
Collecting pynput
  Using cached pynput-1.7.5-py2.py3-none-any.whl (87 kB)
Collecting screeninfo
  Using cached screeninfo-0.8-py3-none-any.whl (14 kB)
Collecting entmax
  Using cached entmax-1.0.tar.gz (7.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /mnt/fast/LaTeX-OCR/ltx-ocr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mtqqac1u
         cwd: /tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/setup.py", line 2, in <module>
        from entmax import __version__
      File "/tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/entmax/__init__.py", line 3, in <module>
        from entmax.activations import sparsemax, entmax15, Sparsemax, Entmax15
      File "/tmp/pip-install-ym_dyhhm/entmax_fb480f8d2f9f4003bc587e6e90a0966a/entmax/activations.py", line 13, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/05/da/27fc966a4786e933778161644a1a1a228148b296d2059682799c4a8ecff8/entmax-1.0.tar.gz#sha256=1cd9721c34935824e071c8c20900711cad60c3d84bc9e4668f3b7a8873bf62cf (from https://pypi.org/simple/entmax/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
INFO: pip is looking at multiple versions of tokenizers to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement entmax (from x-transformers)
ERROR: No matching distribution found for entmax
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/mnt/fast/LaTeX-OCR/ltx-ocr/bin/python3 -m pip install --upgrade pip' command.

**Comment by jave** [comment]
also tried setting the torch version to 1.7.1, since that was the version that the docs said was being tested, but it didnt help

**Comment by lukas-blecher** [comment]
what happens if you install torch first and then run `pip install -r requirements.txt`?
I will set up a new environment and try to replicate the error. For some reason the `entmax` library seems to make problems. I don't even need it, but it's required by `x_tranformers`.
Or what happens if you install with this `requirements.txt`?
```cpp
tqdm>=4.47.0
munch>=2.5.0
torch>=1.7.1
torchvision>=0.8.1
opencv_python_headless>=4.1.1.26
requests>=2.22.0
einops>=0.3.0
chardet>=3.0.4
x_transformers==0.15.0
imagesize>=1.2.0
transformers>=4.2.2
tokenizers==0.9.4
numpy>=1.19.5
Pillow>=8.1.0
PyYAML>=5.4.1
torchtext>=0.6.0
albumentations>=0.5.2
pandas>=1.0.0
timm
python-Levenshtein>=0.12.2

# GUI
PyQt5
PyQtWebEngine
pynput
screeninfo
```

**Comment by jave** [comment]
The new req file didnt seem to help, i tried bot updating the existing venv, and making a new one

**Comment by jave** [comment]
I tried this:

pip install torch 

in the broken venv from the 1st pip install requirements.txt. 

This proceeded to install torch. Then, I reran the pip install requirements.txt, and the entire installation finished.

My guess is that there is something wrong with the dependency tree so that pip install doesnt install things in the correct order.
But its just a hunch.

**Comment by lukas-blecher** [comment]
When I ran the new requirements.txt in a fresh virtual environment it worked out fine.
I also found out that the transformers version does not work with the required tokenizer version, so I also fixed it.
Thanks for opening the issue
