### ISSUE TITLE
How to train model on handwritten dataset

### ISSUE THREAD

**Issue by SaadAliHafiz** [lukas-blecher/LaTeX-OCR#80]
We need to generate latex from a handwritten equation. We followed the steps mentioned in README on how to train the model

`python dataset/dataset.py --equations dataset\CROHME_math.txt --images dataset\images --tokenizer dataset/tokenizer.json --out dataset.pkl`

`python train.py --config settings\config.yaml`

It was taking approx 9hrs to complete one epoch(without GPU)

were we using the right approach?

What are the steps to train the model on the given handwritten CROHME_math dataset to predict latex from the handwritten equation?

**Comment by lukas-blecher** [comment]
Yes I think everything is in order here. Did the validation metrics improve already?
The model takes many epochs to converge. I definitely recommend using a GPU. Maybe you can get it to work on a google colab.
