### ISSUE TITLE
Tokenizer.json for CROHME_math dataset

### ISSUE THREAD

**Issue by SaadAliHafiz** [lukas-blecher/LaTeX-OCR#84]
Do I need to create a new tokenizer.json file for the CROHME_math dataset or should I use this existent tokenizer.json file?

If we need to create a new tokenizer.json file then how can I make it.

**Comment by lukas-blecher** [comment]
You can use the existing one though it was pointed out that the vocab size does not fit the model parmeters (#78) so maybe go ahead and generate a new one, as described in the README
>```
>python dataset/dataset.py --equations path_to_textfile --vocab-size 8000 --out tokenizer.json
>```
