### ISSUE TITLE
Zero Division Error in eval.py

### ISSUE THREAD

**Issue by Agha-Muqarib** [lukas-blecher/LaTeX-OCR#85]
Okay, so I was trying to get to compute BLEU score via eval.py by executing the following command:

`python3 "/content/drive/My Drive/LaTeX-OCR-main/eval.py"`

I got the following error when it reached 15%.

`BLEU: 0.010, ED: 2.59e+01:  15% 109/709 [21:25<1:57:53, 11.79s/it]
Traceback (most recent call last):
  File "/content/drive/My Drive/LaTeX-OCR-main/eval.py", line 117, in <module>
    evaluate(model, dataset, args, num_batches=parsed_args.num_batches)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/My Drive/LaTeX-OCR-main/eval.py", line 65, in evaluate
    edit_dists.append(distance(post_process(predi), ts)/len(ts))
ZeroDivisionError: division by zero`

What seems to be the issue? How can I fix it?

**Comment by lukas-blecher** [comment]
The issue was when the model predicts an empty string which never happend when I used it but it's fixed now.
Thanks!

**Comment by Agha-Muqarib** [comment]
Okay so do I update my eval.py file to fix it or what?

**Comment by Agha-Muqarib** [comment]
That's great, I'll try it now. Thanks!
