### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by yogesh-dahake** [lukas-blecher/LaTeX-OCR#88]
Not able to download the torch (and some other dependencies) on windows 11 with i3 11th Gen.
see attached [screenshot.](https://user-images.githubusercontent.com/98638741/151655807-0c6668b5-82f4-4b77-b48a-bb6aca8bb51f.png)

**Comment by lukas-blecher** [comment]
Please lool if you can find the solution in the previous issue: #72
