### ISSUE TITLE
Will changing the aspect ratio get better results

### ISSUE THREAD

**Issue by CatchDr** [lukas-blecher/LaTeX-OCR#93]
The difference is usually four times wider, but I can't see that the difference is usually four times wider

**Comment by CatchDr** [comment]
I observed that the width gap is very large, the popularity is two to double, Stock Photo 224 is a good time will not be good

**Comment by CatchDr** [comment]
机器翻译效果很差，我只好中文表达我的观点了，可以使用页面翻译转为英语，我观察到宽高差距很大，通常相差两到四倍，图像不选择224而是不同数值会不会更好

**Comment by lukas-blecher** [comment]
I'm sorry, but I don't really understand what you mean. In general the images are wider because the equations depicted are usually only one line long. So the dimensions are expected to be wider than higher. This should not be a problem to the model the way I coded it.

**Comment by CatchDr** [comment]
抱歉可能我描述得不是很清楚，举个例子，一张图片大小为宽800 高128，通常把它变为224*224的大小，我是对这个224不理解，虽然绝大多数图像都是宽高相同的，但是公式图像绝大多数相差几倍，设置不同宽高会不会更适合这个任务呢

**Comment by CatchDr** [comment]
![image](https://user-images.githubusercontent.com/49591435/152365569-bf855d3c-0cba-4362-bc72-3af976cf4c2b.png)


这个224是什么意思呢

**Comment by lukas-blecher** [comment]
Not much. This value sets the maximum image size and is overwritten here: https://github.com/lukas-blecher/LaTeX-OCR/blob/b5217d2b9938b7d7c7f4f27c581985c9c112f254/models.py#L121

standard value is a tuple of (672, 192) so 3.5 times wider.

**Comment by CatchDr** [comment]
在yaml文件中我找到了这个参数，也就是说宽高是一个范围而不是传统cnn那样固定大小是么

**Comment by lukas-blecher** [comment]
CNNs can handle different image sizes perfectly. In fact the backbone of this model is also a CNN. It's just often the dataset that is limited to a fixed image size. 
But yes, you are correct. The model can handle all image sizes that are divisible by 32 and lie between the min and max size.

**Comment by CatchDr** [comment]
这个项目您是否写了论文，作为一个新手我想阅读论文的思路更容易帮我理解

**Comment by lukas-blecher** [comment]
No I did not write a paper. But you can read the paper it is based on: https://arxiv.org/abs/2010.11929
