### ISSUE TITLE
Repo/project name `LaTeX-OCR` versus `pix2tex`

### ISSUE THREAD

**Issue by frankier** [lukas-blecher/LaTeX-OCR#95]
Hi! I wonder whether it would be possible to make the repo name consistent with the project name elsewhere which seems to be pix2tex? I think doing this soon would help avoid confusion down the road. As far as I know, GitHub lets you move repos.

**Comment by lukas-blecher** [comment]
Hi,
for now I think I'll keep it that way. I like both names and I'm not sure how there could be confusion here.
I might come back to it later, especially regarding your pull request #94. Thanks for that by the way

**Comment by frankier** [comment]
Okay! I suppose it's less confusing than a minor inconsistency, which could make people cross referencing from a name in a package repository momentarily unsure if they were in the right place. I don't have a particular opinion on one name or another, but fair enough if you want to defer making a decision on this.
