### ISSUE TITLE
entmax installation problem

### ISSUE THREAD

**Issue by abirdiehard** [lukas-blecher/LaTeX-OCR#96]
During the installation in windows 10 following error came. could please guide me to solve this issue...

Collecting entmax
  Using cached entmax-1.0.tar.gz (7.2 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
  command: 'c:\users\mishty\appdata\local\programs\python\python36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-_nucjrpp\\entmax_3ef33a7b64d243c08c539f36ed740e3c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-_nucjrpp\\entmax_3ef33a7b64d243c08c539f36ed740e3c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mishty\AppData\Local\Temp\pip-pip-egg-info-6mlw4d62'
       cwd: C:\Users\Mishty\AppData\Local\Temp\pip-install-_nucjrpp\entmax_3ef33a7b64d243c08c539f36ed740e3c\
  Complete output (9 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Mishty\AppData\Local\Temp\pip-install-_nucjrpp\entmax_3ef33a7b64d243c08c539f36ed740e3c\setup.py", line 2, in <module>
      from entmax import __version__
    File "C:\Users\Mishty\AppData\Local\Temp\pip-install-_nucjrpp\entmax_3ef33a7b64d243c08c539f36ed740e3c\entmax\__init__.py", line 3, in <module>
      from entmax.activations import sparsemax, entmax15, Sparsemax, Entmax15
    File "C:\Users\Mishty\AppData\Local\Temp\pip-install-_nucjrpp\entmax_3ef33a7b64d243c08c539f36ed740e3c\entmax\activations.py", line 13, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/05/da/27fc966a4786e933778161644a1a1a228148b296d2059682799c4a8ecff8/entmax-1.0.tar.gz#sha256=1cd9721c34935824e071c8c20900711cad60c3d84bc9e4668f3b7a8873bf62cf (from https://pypi.org/simple/entmax/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement entmax (from x-transformers) (from versions: 1.0)
ERROR: No matching distribution found for entmax

**Comment by lukas-blecher** [comment]
I don't know why this is happening, but you're not the first one. See here: https://github.com/lukas-blecher/LaTeX-OCR/issues/72#issuecomment-1003180696
Basically you need to install pytorch manually first for some reason.

**Comment by frankier** [comment]
The reason is that entmax imports torch in its `setup.py`. See https://github.com/deep-spin/entmax/pull/25

**Comment by lukas-blecher** [comment]
Thanks for the info! Hopefully this will be merged soon.

**Comment by frankier** [comment]
Fixed now, so updating entmax should fix this.
