### ISSUE TITLE
Running setup.py install for python-Levenshtein ... error

### ISSUE THREAD

**Issue by abirdiehard** [lukas-blecher/LaTeX-OCR#97]
In windows 10 for "entmax installation problem" as suggested installed pytorch manually and it worked entmax got installed but after further installing other dependencies it again stopped at "**setup.py install for python-Levenshtein ... error**" and showed following error. Please help me to resolve this error..

Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\mishty\appdata\local\programs\python\python36\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations>=0.5.2->-r requirements.txt (line 17)) (3.1.0)
Using legacy 'setup.py install' for python-Levenshtein, since package 'wheel' is not installed.
Installing collected packages: python-Levenshtein, PyQtWebEngine, pynput, pandas, munch, imagesize, albumentations
    Running setup.py install for python-Levenshtein ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mishty\appdata\local\programs\python\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-y79ykp8_\\python-levenshtein_d2bc5e03a87946458321696f730eb269\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-y79ykp8_\\python-levenshtein_d2bc5e03a87946458321696f730eb269\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mishty\AppData\Local\Temp\pip-record-ylphglmw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\mishty\appdata\local\programs\python\python36\Include\python-Levenshtein'
         cwd: C:\Users\Mishty\AppData\Local\Temp\pip-install-y79ykp8_\python-levenshtein_d2bc5e03a87946458321696f730eb269\
    Complete output (27 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.6\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.6\Levenshtein
    running egg_info
    writing python_Levenshtein.egg-info\PKG-INFO
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.6\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.6\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\mishty\appdata\local\programs\python\python36\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-y79ykp8_\\python-levenshtein_d2bc5e03a87946458321696f730eb269\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mishty\\AppData\\Local\\Temp\\pip-install-y79ykp8_\\python-levenshtein_d2bc5e03a87946458321696f730eb269\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mishty\AppData\Local\Temp\pip-record-ylphglmw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\mishty\appdata\local\programs\python\python36\Include\python-Levenshtein' Check the logs for full command output.

**Comment by lukas-blecher** [comment]
Did you read the error log? It clearly states 
> Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

On a side note, you don't need this package if you only want to use the pretrained model. It's only required if you wanted reproduce the evaluation metrics.

**Comment by abirdiehard** [comment]
Ok I wanted to use pretrained model only...after getting this error when
run on cmd python pix2tex.py or python gyi.py. Nothing happened...
